### ISSUE TITLE
HTTP getcontent is not secure

### ISSUE THREAD

**Issue by mxmo0rhuhn** [phgamper/markdown_blog#19]
HTTP getcontent does not verify ssl certicicates until Version 5.6🚥🚥

**Comment by rethab** [comment]
Some background: https://wiki.php.net/rfc/tls-peer-verification

**Comment by phgamper** [comment]
It is recommend to use markdown_blog with php >= Version 5.6

See the sample installation in the provided Dockerfile below:
```
root@425085b86240:/var/www/html# php --version
PHP 5.6.13 (cli) (built: Sep 10 2015 00:34:06) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

Nevertheless, thanks a lot for the input!
