### ISSUE TITLE
Static link for blog posts / pretty URLs

### ISSUE THREAD

**Issue by mxmo0rhuhn** [phgamper/markdown_blog#20]
It would be nice if you could send a static link for a special blog post
Therefore namespaces instead of URL Parameters should be used for the different ressources

**Comment by phgamper** [comment]
pretty url implemented, detail view of post pending

**Comment by phgamper** [comment]
Closed by the followig commits:

https://github.com/phgamper/markdown_blog/commit/19ed014d76771dded5c203d602f6e0ecadd0ccb5

https://github.com/phgamper/markdown_blog/commit/561fbdb78436f579a5f196074fe2bd65ca7cc9d7
