### ISSUE TITLE
Send HTTP 404 in case of "Warning! The requested URL is not available."

### ISSUE THREAD

**Issue by mxmo0rhuhn** [phgamper/markdown_blog#29]
If a URL is not known a normal error page with the warning "Warning! The requested URL is not available." is delivered with HTTP return code 200 OK. 

This behaviour is great for humans but really bad for spiders etc.
It would be better if 404 is returned as HTTP code as well as a page for humans to read. 
=> [Github like behaviour](https://github.com/not_existing)

**Comment by phgamper** [comment]
Works on a local apache instance but not behind an nginx

**Comment by phgamper** [comment]
Setting the HTTP response code was moved up. Seems that the creation of the Model causes the undesired behaviour.
