### ISSUE TITLE
Input Validation Vulnerability: Image Resize

### ISSUE THREAD

**Issue by groggi** [phgamper/markdown_blog#38]
`/public/image.php` does not validate `src` and `width` GET parameters and passes them on to `exec`. This provides an attacker with full shell access under the webserver's user.

Executing a command: `BASE_URL/image.php?src=%20;%20cat%20/etc/passwd%20%3E%3E%20cache/foo;&width=100`

Accessing output:
`BASE_URL/cache/foo`

**Comment by groggi** [comment]
Possible way to mitigate while keeping the functionality intact:
- Allow only `a-z`, `A-Z`, `0-9`, `-`, `_` and `/` as part of the path
- Make sure `src` is a valid POSIX path (or valid path for the system). Without accessing it!
- Add a whitelist of rooted POSIX paths to the config file and make sure the provided `src` is a file below one of the whitelisted paths (i.e. prefix match)
- Maybe: check if the file exists, not sure which attack vectors it mitigates, but it would reduce the risk of unexpected error outputs being put into the output file
- If any of the above checks fail -> abort and log. Be careful with what you log, might introduce a similar vulnerability. In addition, might lead to a DoS if the attacker calls the page lots of times with invalid input.
- Make sure `width` is a number
- Make sure `width` is inside a sane range (e.g. 200 < `width` < 4000)

Of course, the best solution would be to remove on-the-fly image resizes.

**Comment by phgamper** [comment]
Hi Gregor, many thanks for reporting this bug. The PHP script now escapes command line arguments first before executing the command. This should do the trick. 

More infos [here](http://php.net/manual/en/function.escapeshellarg.php)
